CREATE TABLE cliente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(63),
    cognome VARCHAR(63),
    username VARCHAR(63),
    password VARCHAR(63),
    saldo REAL
);

CREATE TABLE venditore (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(63),
    cognome VARCHAR(63),
    username VARCHAR(63),
    password VARCHAR(63),
    saldo REAL,
    feedback INTEGER
);

CREATE TABLE disco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(63),
    descrizione VARCHAR (4095),
    copertina VARCHAR(255),
    disponibilità INTEGER,
    prezzo REAL,
    id_venditore INTEGER,
    FOREIGN KEY (id_venditore) REFERENCES venditore(id)
);